### ISSUE TITLE
Configuration in Docker Container

### ISSUE THREAD

**Issue by djtimca** [TradeFace/tuyagateway#78]
I can't figure out how to configure the MQTT gateway when built as a docket container. I have tried modifying the docker file to add the config to the application call and have tried to edit the config file on the running docket but neither works. 

How do I assign the IP, user, and password in a docker install?

**Comment by TradeFace** [comment]
you can make a share volume to /application/etc/
And put your custom tuyagateway.conf in there.

**Comment by djtimca** [comment]
Thanks - I have set up the /use/src/app/etc volume and updated the tuya gateway.conf there then verified via portainer console that the contents are correct in that file. 

I still don't see any Mosquitto login requests from that container which makes me think that it isn't picking up that config file. 

I tested by sending an MQTT command and listening and I can see the command but no responses and nothing in the Mosquitto log. 

Is there anywhere in the container I can find some logging?

**Comment by TradeFace** [comment]
Not directly. It logs only to screen (https://github.com/tradeface/tuyagateway/wiki//Commandline-options) 
I run HA and tuyagateway with docker-compose. That seems to run without a problem. My `docker-compose.yml` below. 

tuyaGateway looks in two locations for the config. in 
```
"./etc/tuyagateway.conf",
"/usr/local/etc/tuyagateway.conf",
"/etc/tuyagateway.conf",
```
And is allways ovewritten by the commandline options.


```
version: '3'
services:
  homeassistant:
    ports: 
      - "8123:8123"
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
      - ./homeassistant/ssh:/root/.ssh
    environment:
      - TZ=Europe/Amsterdam
    restart: always
    network_mode: host
    depends_on: 
      - mysql
  mysql:
    build: ./mysql
    container_name: mysql
    hostname: mysql 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ./mysql/data:/var/lib/mysql
    network_mode: host
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3306"]
        interval: 30s
        timeout: 10s
        retries: 5
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: always
    network_mode: host
  tuyamqtt:
    image: "tuyamqtt:latest"
    hostname: tuyamqtt 
    container_name: tuyamqtt   
    working_dir: /usr/src/app    
    volumes:
      - ./tuyamqtt/config:/usr/src/app/etc    
    command: "tuyamqtt"
    restart: always
    network_mode: host
  gismocaster:
    ports:
      - "8000:8000"
    image: "gismocaster:latest"
    hostname: gismocaster
    container_name: gismocaster
    working_dir: /usr/src/app
    volumes:
      - ./gismocaster/etc:/usr/src/app/etc
      - ./gismocaster/var:/usr/src/app/var
    command: "python3 web/manage.py runserver 0.0.0.0:8000 --noreload"
    restart: always
    network_mode: host


```
